import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction', // This will be the global introduction page
      label: 'Introduction to Physical AI & Robotics',
    },
    {
      type: 'doc',
      id: 'setup-guide',
      label: 'Development Environment Setup',
    },
    {
      type: 'doc',
      id: 'hardware-requirements',
      label: 'Hardware & Software Requirements',
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'ROS 2 Fundamentals',
        description: 'Learn the core concepts of ROS 2 for robotic control.',
        slug: '/category/module-1-ros2',
      },
      items: [{type: 'autogenerated', dirName: '01-module-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Robot Simulation with Gazebo & Unity',
        description: 'Explore realistic physics and human-robot interaction in simulated environments.',
        slug: '/category/module-2-digital-twin',
      },
      items: [{type: 'autogenerated', dirName: '02-module-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'generated-index',
        title: 'AI Perception & Navigation with NVIDIA Isaac',
        description: 'Develop intelligent behaviors for robots using NVIDIA Isaac Sim and Isaac ROS.',
        slug: '/category/module-3-isaac-ai',
      },
      items: [{type: 'autogenerated', dirName: '03-module-isaac-sim'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'generated-index',
        title: 'Conversational Robotics & VLA Systems',
        description: 'Integrate GPT models to enable natural language interaction with humanoid robots.',
        slug: '/category/module-4-vla',
      },
      items: [{type: 'autogenerated', dirName: '04-module-vla'}],
    },
    {
      type: 'doc',
      id: 'capstone-project',
      label: 'Capstone Project: Autonomous Humanoid',
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary',
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'Frequently Asked Questions',
    },
  ],
};

export default sidebars;
